name = "themaplepitch-app"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "dev.themaplepitch.ca", custom_domain = true }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
